# This is a basic workflow to help you get started with Actions

name: Deploy to GAE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/gcplab-336520/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'gcplabgithubactionaccount@gcplab-336520.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: src/main/appengine/app.yaml
        version: v1
        
    - id: Test
      run: curl "${{ steps.deploy.outputs.url }}"
